import type { FounderInputRecord } from "../schemas/approvals";

/**
 * Founder-supplied proposed seed terms.
 * Public pitch may describe these as PROPOSED copy in seedProposition.ts.
 * They are not approved_public founder-input facts and remain confidential
 * in this registry until legal review completes.
 */
export const fundingInput: FounderInputRecord[] = [
  {
    id: "funding-round-type",
    value: "Post-money SAFE (proposed)",
    status: "under_review",
    approvedForPublic: false,
    approvedForInvestorOnly: true,
    confidential: true,
    owner: "Founder / Counsel",
    reviewNotes: "Proposed public wording lives in seedProposition copy. Not completed financing.",
  },
  {
    id: "funding-target-amount",
    value: "A$3M (proposed)",
    status: "under_review",
    approvedForPublic: false,
    approvedForInvestorOnly: true,
    confidential: true,
    owner: "Founder",
    reviewNotes: "Proposed target raise for public pitch, labelled proposed / subject to documentation.",
  },
  {
    id: "funding-valuation-cap",
    value: "A$12M post-money cap (proposed)",
    status: "under_review",
    approvedForPublic: false,
    approvedForInvestorOnly: true,
    confidential: true,
    owner: "Founder / Counsel",
    reviewNotes: "Proposed cap, not an established current valuation.",
  },
  {
    id: "funding-target-runway",
    value: "12 months (proposed)",
    status: "under_review",
    approvedForPublic: false,
    approvedForInvestorOnly: true,
    confidential: true,
    owner: "Founder",
  },
  {
    id: "funding-seed-allocation",
    value: "Approximately 25% (proposed, conceptual SAFE-round economics)",
    status: "under_review",
    approvedForPublic: false,
    approvedForInvestorOnly: true,
    confidential: true,
    owner: "Founder / Counsel",
    reviewNotes: "Not a claim that investors currently own 25%.",
  },
  {
    id: "funding-primary-markets",
    value: "Australia + Vietnam",
    status: "under_review",
    approvedForPublic: false,
    approvedForInvestorOnly: true,
    confidential: true,
    owner: "Founder",
  },
  {
    id: "funding-target-close",
    value: "[TARGET CLOSE REQUIRED]",
    status: "missing",
    approvedForPublic: false,
    approvedForInvestorOnly: true,
    confidential: true,
    owner: "Founder",
  },
  {
    id: "funding-closing-model",
    value: "[CLOSING MODEL REQUIRED]",
    status: "missing",
    approvedForPublic: false,
    approvedForInvestorOnly: true,
    confidential: true,
    owner: "Founder / Counsel",
    reviewNotes: "Pitch diligence states proposed rolling close — to confirm.",
  },
  {
    id: "funding-first-close",
    value: "[FIRST-CLOSE THRESHOLD REQUIRED]",
    status: "missing",
    approvedForPublic: false,
    approvedForInvestorOnly: true,
    confidential: true,
    owner: "Founder / Counsel",
  },
  {
    id: "funding-minimum",
    value: "[MINIMUM INVESTMENT REQUIRED]",
    status: "missing",
    approvedForPublic: false,
    approvedForInvestorOnly: true,
    confidential: true,
    owner: "Founder / Counsel",
  },
  {
    id: "funding-oversubscription",
    value: "[OVERSUBSCRIPTION REQUIRED]",
    status: "missing",
    approvedForPublic: false,
    approvedForInvestorOnly: true,
    confidential: true,
    owner: "Founder / Counsel",
  },
  {
    id: "funding-eligibility",
    value: "[INVESTOR ELIGIBILITY REQUIRED]",
    status: "missing",
    approvedForPublic: false,
    approvedForInvestorOnly: true,
    confidential: true,
    owner: "Counsel",
  },
];
