import type { ProductCapability } from "../schemas/types";

/**
 * Capability registry — Phase 2 audit.
 * Code existence ≠ live commercial product.
 * Investor-facing evidenceNote only; internalNotes never rendered.
 */
export const productCapabilities: ProductCapability[] = [
  {
    id: "cap-ai-storefront",
    title: { en: "AI-assisted storefront creation", vi: "Tạo storefront có hỗ trợ AI" },
    shortDescription: {
      en: "Create digital business and storefront experiences from supplied business information.",
      vi: "Tạo trải nghiệm doanh nghiệp số và storefront từ thông tin doanh nghiệp được cung cấp.",
    },
    category: "product_creation",
    proofGroup: "product_creation",
    status: "development",
    proofType: "repository",
    evidenceNote:
      "Storefront API and related platform routes are implemented; commercial “live MVP” status requires founder confirmation.",
    internalNotes: "adjacent-server/routes/storefront.js",
    confirmationRequired: true,
    public: true,
  },
  {
    id: "cap-business-import",
    title: { en: "Business Import Kernel", vi: "Business Import Kernel" },
    shortDescription: {
      en: "A structured system for acquiring, interpreting and preparing business information for platform use.",
      vi: "Hệ thống có cấu trúc để thu thập, diễn giải và chuẩn bị thông tin doanh nghiệp cho nền tảng.",
    },
    category: "product_creation",
    proofGroup: "product_creation",
    status: "development",
    proofType: "manual_confirmation_required",
    evidenceNote:
      "Described as an active platform direction; module boundaries require founder/engineering confirmation before upgrading maturity.",
    confirmationRequired: true,
    public: true,
  },
  {
    id: "cap-structured-drafts",
    title: { en: "Structured draft generation", vi: "Sinh bản nháp có cấu trúc" },
    shortDescription: {
      en: "Generate structured drafts for business presence and content from inputs.",
      vi: "Sinh bản nháp có cấu trúc cho hiện diện và nội dung doanh nghiệp từ đầu vào.",
    },
    category: "product_creation",
    proofGroup: "product_creation",
    status: "development",
    proofType: "manual_confirmation_required",
    confirmationRequired: true,
    public: true,
  },
  {
    id: "cap-storefront-localization",
    title: { en: "Storefront localization", vi: "Bản địa hóa storefront" },
    shortDescription: {
      en: "AI-assisted localization of storefront content across languages and markets.",
      vi: "Bản địa hóa storefront có hỗ trợ AI theo ngôn ngữ và thị trường.",
    },
    category: "language",
    proofGroup: "business_intelligence",
    status: "development",
    proofType: "manual_confirmation_required",
    confirmationRequired: true,
    public: true,
  },
  {
    id: "cap-conversation-localization",
    title: { en: "Conversation localization", vi: "Bản địa hóa hội thoại" },
    shortDescription: {
      en: "AI-assisted localization for business conversations — non-authoritative, preference-aware.",
      vi: "Bản địa hóa hội thoại kinh doanh có hỗ trợ AI — không mang tính phán quyết tuyệt đối, theo tùy chọn.",
    },
    category: "language",
    proofGroup: "business_intelligence",
    status: "development",
    proofType: "manual_confirmation_required",
    confirmationRequired: true,
    public: true,
  },
  {
    id: "cap-cultural-tone",
    title: { en: "Cultural and tone preferences", vi: "Tùy chỉnh văn hóa & giọng điệu" },
    shortDescription: {
      en: "Durable preference-driven tone and cultural adaptation for communications.",
      vi: "Thích ứng giọng điệu và yếu tố văn hóa theo tùy chọn bền vững.",
    },
    category: "language",
    proofGroup: "business_intelligence",
    status: "development",
    proofType: "manual_confirmation_required",
    confirmationRequired: true,
    public: true,
  },
  {
    id: "cap-glossary-learning",
    title: { en: "Glossary learning", vi: "Học thuật ngữ chuyên ngành" },
    shortDescription: {
      en: "Learn business-specific vocabulary over time to improve localization quality.",
      vi: "Học từ vựng chuyên biệt của doanh nghiệp theo thời gian để cải thiện bản địa hóa.",
    },
    category: "language",
    proofGroup: "business_intelligence",
    status: "planned",
    proofType: "none",
    public: true,
  },
  {
    id: "cap-ai-performer",
    title: { en: "Performer", vi: "Performer" },
    shortDescription: {
      en: "An orchestration layer that prepares and executes business tasks within defined policies and boundaries.",
      vi: "Lớp điều phối chuẩn bị và thực thi tác vụ doanh nghiệp trong chính sách và phạm vi đã định.",
    },
    category: "agents",
    proofGroup: "business_intelligence",
    status: "development",
    proofType: "repository",
    evidenceNote:
      "Performer command, chat and share execution routes are implemented with session-history hooks.",
    internalNotes: "adjacent-server/routes/performer.js",
    confirmationRequired: true,
    public: true,
  },
  {
    id: "cap-readiness-preflight",
    title: { en: "Readiness and preflight checks", vi: "Kiểm tra sẵn sàng & preflight" },
    shortDescription: {
      en: "Task-specific readiness checks that support controlled execution boundaries.",
      vi: "Kiểm tra sẵn sàng theo tác vụ để hỗ trợ ranh giới thực thi có kiểm soát.",
    },
    category: "business_intelligence",
    proofGroup: "business_intelligence",
    status: "development",
    proofType: "manual_confirmation_required",
    confirmationRequired: true,
    public: true,
  },
  {
    id: "cap-business-memory",
    title: { en: "Business knowledge foundations", vi: "Nền tảng tri thức doanh nghiệp" },
    shortDescription: {
      en: "Durable preferences, relationships and reusable context that inform later workflows.",
      vi: "Tùy chọn, quan hệ và ngữ cảnh tái sử dụng bền vững phục vụ các quy trình sau.",
    },
    category: "intelligence",
    proofGroup: "business_intelligence",
    status: "development",
    proofType: "manual_confirmation_required",
    evidenceNote:
      "Persistent memory hooks appear in platform services; a fully autonomous universal business graph is not claimed.",
    confirmationRequired: true,
    public: true,
  },
  {
    id: "cap-business-graph",
    title: { en: "Structured business knowledge", vi: "Tri thức doanh nghiệp có cấu trúc" },
    shortDescription: {
      en: "Structured relationships across identity, products, customers, devices, content and operations — under active development.",
      vi: "Quan hệ có cấu trúc giữa định danh, sản phẩm, khách hàng, thiết bị, nội dung và vận hành — đang phát triển.",
    },
    category: "intelligence",
    proofGroup: "business_intelligence",
    status: "development",
    proofType: "manual_confirmation_required",
    confirmationRequired: true,
    public: true,
  },
  {
    id: "cap-growth-engine",
    title: { en: "Growth Engine", vi: "Growth Engine" },
    shortDescription: {
      en: "Infrastructure for attribution, partner participation and value allocation across business networks — not MLM.",
      vi: "Hạ tầng ghi nhận nguồn, tham gia đối tác và phân bổ giá trị trong mạng doanh nghiệp — không phải MLM.",
    },
    category: "growth",
    proofGroup: "growth",
    status: "development",
    proofType: "repository",
    evidenceNote:
      "Rewards and behaviour infrastructure exists; Partner Capital Recovery / Partner Pass commercial readiness requires confirmation.",
    internalNotes: "adjacent-server/routes/rewards.js",
    confirmationRequired: true,
    public: true,
  },
  {
    id: "cap-partner-pass",
    title: { en: "Partner Pass", vi: "Partner Pass" },
    shortDescription: {
      en: "Partner experience linked to natural introductions and attributable value participation.",
      vi: "Trải nghiệm đối tác gắn với giới thiệu tự nhiên và tham gia giá trị có thể ghi nhận.",
    },
    category: "growth",
    proofGroup: "growth",
    status: "development",
    proofType: "manual_confirmation_required",
    confirmationRequired: true,
    public: true,
  },
  {
    id: "cap-partner-attribution",
    title: { en: "Partner attribution", vi: "Ghi nhận nguồn đối tác" },
    shortDescription: {
      en: "Attribute opportunities from natural partner and customer references with policy-aware tracking.",
      vi: "Ghi nhận cơ hội từ giới thiệu tự nhiên của đối tác và khách hàng theo chính sách.",
    },
    category: "growth",
    proofGroup: "growth",
    status: "development",
    proofType: "manual_confirmation_required",
    confirmationRequired: true,
    public: true,
  },
  {
    id: "cap-smart-display-runtime",
    title: { en: "Shared display runtime", vi: "Runtime màn hình dùng chung" },
    shortDescription: {
      en: "Shared runtime contracts for digital displays across platforms.",
      vi: "Hợp đồng runtime dùng chung cho màn hình số đa nền tảng.",
    },
    category: "devices",
    proofGroup: "device_distribution",
    status: "development",
    proofType: "repository",
    evidenceNote: "Device-engine modules for pairing, heartbeat, playlist and repair are present in the codebase.",
    internalNotes: "adjacent-server/engines/device",
    public: true,
  },
  {
    id: "cap-android-player",
    title: { en: "Android display player", vi: "Trình phát màn hình Android" },
    shortDescription: {
      en: "Native Android playback path for Cardbey displays.",
      vi: "Lộ trình phát native Android cho màn hình Cardbey.",
    },
    category: "devices",
    proofGroup: "device_distribution",
    status: "development",
    proofType: "manual_confirmation_required",
    evidenceNote: "Platform direction with related device APIs; physical validation status requires founder confirmation.",
    confirmationRequired: true,
    public: true,
  },
  {
    id: "cap-webos",
    title: { en: "LG webOS display application", vi: "Ứng dụng màn hình LG webOS" },
    shortDescription: {
      en: "webOS application path for commercial displays.",
      vi: "Ứng dụng webOS cho màn hình thương mại.",
    },
    category: "devices",
    proofGroup: "device_distribution",
    status: "development",
    proofType: "manual_confirmation_required",
    confirmationRequired: true,
    public: true,
  },
  {
    id: "cap-tizen",
    title: { en: "Samsung Tizen support", vi: "Hỗ trợ Samsung Tizen" },
    shortDescription: {
      en: "Planned Tizen support for additional commercial screens.",
      vi: "Hỗ trợ Tizen dự kiến cho thêm màn hình thương mại.",
    },
    category: "devices",
    proofGroup: "device_distribution",
    status: "planned",
    proofType: "none",
    public: true,
  },
  {
    id: "cap-device-pairing",
    title: { en: "Device pairing", vi: "Ghép nối thiết bị" },
    shortDescription: {
      en: "Secure pairing flow between business accounts and devices.",
      vi: "Luồng ghép nối an toàn giữa tài khoản doanh nghiệp và thiết bị.",
    },
    category: "devices",
    proofGroup: "device_distribution",
    status: "development",
    proofType: "repository",
    evidenceNote: "Request/complete pairing modules are implemented in the device engine.",
    internalNotes: "adjacent-server/engines/device/requestPairing.ts",
    public: true,
  },
  {
    id: "cap-playlist",
    title: { en: "Playlist synchronization", vi: "Đồng bộ playlist" },
    shortDescription: {
      en: "Push, confirm and recover display playlists across the device network.",
      vi: "Đẩy, xác nhận và phục hồi playlist trên mạng thiết bị.",
    },
    category: "devices",
    proofGroup: "device_distribution",
    status: "development",
    proofType: "repository",
    evidenceNote: "Playlist push and readiness confirmation paths exist in the device engine.",
    internalNotes: "adjacent-server/engines/device/pushPlaylist.ts",
    public: true,
  },
  {
    id: "cap-signage-scheduling",
    title: { en: "Digital-signage scheduling", vi: "Lập lịch biển hiệu số" },
    shortDescription: {
      en: "Schedule and manage content across connected displays.",
      vi: "Lập lịch và quản lý nội dung trên các màn hình kết nối.",
    },
    category: "devices",
    proofGroup: "device_distribution",
    status: "development",
    proofType: "repository",
    evidenceNote: "Signage and screen control routes are present alongside the device runtime.",
    internalNotes: "adjacent-server/routes/signage.js",
    public: true,
  },
  {
    id: "cap-diagnostics",
    title: { en: "Device diagnostics & media recovery", vi: "Chẩn đoán thiết bị & phục hồi media" },
    shortDescription: {
      en: "Heartbeat, diagnostics and repair-trigger pathways for display reliability.",
      vi: "Heartbeat, chẩn đoán và kích hoạt sửa chữa để tăng độ tin cậy hiển thị.",
    },
    category: "devices",
    proofGroup: "device_distribution",
    status: "development",
    proofType: "repository",
    evidenceNote: "Heartbeat and repair-trigger modules are implemented.",
    internalNotes: "adjacent-server/engines/device/heartbeatV2.ts; triggerRepair.ts",
    public: true,
  },
  {
    id: "cap-admin-agent",
    title: { en: "Business admin agent", vi: "Agent quản trị doanh nghiệp" },
    shortDescription: {
      en: "Permissioned agent support for administrative workflows — assistant, not unsupervised automation.",
      vi: "Agent có phân quyền hỗ trợ quy trình quản trị — trợ lý, không phải tự động hóa thiếu kiểm soát.",
    },
    category: "agents",
    proofGroup: "business_intelligence",
    status: "planned",
    proofType: "none",
    public: true,
  },
  {
    id: "cap-crm-agent",
    title: { en: "CRM agent", vi: "Agent CRM" },
    shortDescription: {
      en: "Customer relationship assistance within owner-defined boundaries.",
      vi: "Hỗ trợ quan hệ khách hàng trong phạm vi chủ doanh nghiệp định nghĩa.",
    },
    category: "agents",
    proofGroup: "business_intelligence",
    status: "planned",
    proofType: "none",
    public: true,
  },
  {
    id: "cap-commerce-ops",
    title: { en: "Commerce operations", vi: "Vận hành thương mại" },
    shortDescription: {
      en: "Operate products, services and selling workflows across channels.",
      vi: "Vận hành sản phẩm, dịch vụ và bán hàng đa kênh.",
    },
    category: "commerce",
    proofGroup: "commerce_experience",
    status: "development",
    proofType: "repository",
    evidenceNote: "Storefront and related commerce-facing routes exist; full launch status requires confirmation.",
    confirmationRequired: true,
    public: true,
  },
  {
    id: "cap-payments",
    title: { en: "Payment integration", vi: "Tích hợp thanh toán" },
    shortDescription: {
      en: "Payment flows connected to Cardbey commerce experiences.",
      vi: "Luồng thanh toán gắn với trải nghiệm thương mại Cardbey.",
    },
    category: "commerce",
    proofGroup: "commerce_experience",
    status: "development",
    proofType: "manual_confirmation_required",
    confirmationRequired: true,
    public: true,
  },
  {
    id: "cap-delivery",
    title: { en: "Delivery and logistics", vi: "Giao nhận và logistics" },
    shortDescription: {
      en: "Delivery coordination capabilities — maturity and commercial readiness to be confirmed.",
      vi: "Khả năng điều phối giao nhận — mức độ chín và sẵn sàng thương mại cần xác nhận.",
    },
    category: "commerce",
    proofGroup: "commerce_experience",
    status: "pilot",
    proofType: "manual_confirmation_required",
    confirmationRequired: true,
    public: true,
  },
];

export function getPublicCapabilities(
  list: ProductCapability[] = productCapabilities
) {
  return list.filter((c) => c.public);
}

export function getCapabilitiesByProofGroup(
  group: NonNullable<ProductCapability["proofGroup"]>,
  list: ProductCapability[] = productCapabilities
) {
  return getPublicCapabilities(list).filter((c) => c.proofGroup === group);
}
