import type { ProductMediaAsset } from "../schemas/types";

/**
 * Media registry — no public render without approval + path + non-rejected status.
 * No customer-identifiable assets without customerApproval.
 */
export const productMedia: ProductMediaAsset[] = [
  {
    id: "media-storefront",
    title: { en: "AI storefront creation", vi: "Tạo storefront AI" },
    caption: { en: "[STOREFRONT SCREENSHOT REQUIRED]", vi: "[CẦN ẢNH STOREFRONT]" },
    longDescription: {
      en: "Browser-framed storefront evidence once approved.",
      vi: "Bằng chứng storefront khung trình duyệt khi được duyệt.",
    },
    capabilityIds: ["cap-ai-storefront"],
    maturity: "development",
    customerSensitive: true,
    customerApproval: false,
    publicApproved: false,
    altText: { en: "Approved storefront screenshot", vi: "Ảnh storefront đã duyệt" },
    displayOrder: 1,
    status: "placeholder",
    displayMode: "browser-frame",
    aspectRatio: "16/10",
    fallbackTreatment: "hide",
  },
  {
    id: "media-import",
    title: { en: "Business import", vi: "Nhập liệu doanh nghiệp" },
    caption: { en: "[BUSINESS IMPORT MEDIA REQUIRED]", vi: "[CẦN MEDIA NHẬP LIỆU]" },
    capabilityIds: ["cap-business-import"],
    maturity: "development",
    customerSensitive: true,
    customerApproval: false,
    publicApproved: false,
    altText: { en: "Business import flow", vi: "Luồng nhập liệu doanh nghiệp" },
    displayOrder: 2,
    status: "placeholder",
    displayMode: "dashboard-frame",
    fallbackTreatment: "hide",
  },
  {
    id: "media-editor",
    title: { en: "Storefront editor", vi: "Trình chỉnh sửa storefront" },
    caption: { en: "[STOREFRONT EDITOR MEDIA REQUIRED]", vi: "[CẦN MEDIA EDITOR]" },
    capabilityIds: ["cap-ai-storefront"],
    maturity: "development",
    customerSensitive: false,
    publicApproved: false,
    altText: { en: "Storefront editor", vi: "Trình chỉnh sửa storefront" },
    displayOrder: 3,
    status: "placeholder",
    displayMode: "browser-frame",
    fallbackTreatment: "hide",
  },
  {
    id: "media-performer",
    title: { en: "Performer workflow", vi: "Quy trình Performer" },
    caption: { en: "[PERFORMER WORKFLOW MEDIA REQUIRED]", vi: "[CẦN MEDIA PERFORMER]" },
    capabilityIds: ["cap-ai-performer"],
    proofIds: ["proof-performer"],
    maturity: "development",
    customerSensitive: false,
    publicApproved: false,
    altText: { en: "Performer workflow", vi: "Quy trình Performer" },
    displayOrder: 4,
    status: "placeholder",
    displayMode: "dashboard-frame",
    fallbackTreatment: "hide",
  },
  {
    id: "media-preflight",
    title: { en: "Preflight / readiness", vi: "Preflight / sẵn sàng" },
    caption: { en: "[PREFLIGHT MEDIA REQUIRED]", vi: "[CẦN MEDIA PREFLIGHT]" },
    capabilityIds: ["cap-readiness-preflight"],
    maturity: "development",
    customerSensitive: false,
    publicApproved: false,
    altText: { en: "Readiness checks", vi: "Kiểm tra sẵn sàng" },
    displayOrder: 5,
    status: "placeholder",
    displayMode: "dashboard-frame",
    fallbackTreatment: "hide",
  },
  {
    id: "media-localization",
    title: { en: "Language Intelligence", vi: "Language Intelligence" },
    caption: { en: "[LOCALIZATION MEDIA REQUIRED]", vi: "[CẦN MEDIA BẢN ĐỊA HÓA]" },
    capabilityIds: ["cap-storefront-localization", "cap-conversation-localization"],
    maturity: "development",
    customerSensitive: false,
    publicApproved: false,
    altText: { en: "Localization comparison", vi: "So sánh bản địa hóa" },
    displayOrder: 6,
    status: "placeholder",
    displayMode: "before-and-after",
    language: "both",
    fallbackTreatment: "hide",
  },
  {
    id: "media-growth-engine",
    title: { en: "Growth Engine", vi: "Growth Engine" },
    caption: { en: "[GROWTH ENGINE MEDIA REQUIRED]", vi: "[CẦN MEDIA GROWTH ENGINE]" },
    capabilityIds: ["cap-growth-engine"],
    proofIds: ["proof-rewards"],
    maturity: "development",
    customerSensitive: false,
    publicApproved: false,
    altText: { en: "Growth Engine UI", vi: "Giao diện Growth Engine" },
    displayOrder: 7,
    status: "placeholder",
    displayMode: "dashboard-frame",
    fallbackTreatment: "hide",
  },
  {
    id: "media-partner-pass",
    title: { en: "Partner Pass", vi: "Partner Pass" },
    caption: { en: "[PARTNER PASS MEDIA REQUIRED]", vi: "[CẦN MEDIA PARTNER PASS]" },
    capabilityIds: ["cap-partner-pass"],
    maturity: "development",
    customerSensitive: false,
    publicApproved: false,
    altText: { en: "Partner Pass UI", vi: "Giao diện Partner Pass" },
    displayOrder: 8,
    status: "placeholder",
    displayMode: "mobile-frame",
    fallbackTreatment: "hide",
  },
  {
    id: "media-display-dashboard",
    title: { en: "Display dashboard", vi: "Bảng điều khiển màn hình" },
    caption: { en: "[DISPLAY DASHBOARD MEDIA REQUIRED]", vi: "[CẦN MEDIA DASHBOARD]" },
    capabilityIds: ["cap-signage-scheduling"],
    maturity: "development",
    customerSensitive: false,
    publicApproved: false,
    altText: { en: "Display dashboard", vi: "Bảng điều khiển màn hình" },
    displayOrder: 9,
    status: "placeholder",
    displayMode: "dashboard-frame",
    fallbackTreatment: "hide",
  },
  {
    id: "media-pairing",
    title: { en: "Device pairing", vi: "Ghép nối thiết bị" },
    caption: { en: "[PAIRING MEDIA REQUIRED]", vi: "[CẦN MEDIA GHÉP NỐI]" },
    capabilityIds: ["cap-device-pairing"],
    proofIds: ["proof-device-pairing"],
    maturity: "development",
    customerSensitive: false,
    publicApproved: false,
    altText: { en: "Device pairing", vi: "Ghép nối thiết bị" },
    displayOrder: 10,
    status: "placeholder",
    displayMode: "mobile-frame",
    fallbackTreatment: "hide",
  },
  {
    id: "media-android-player",
    title: { en: "Android player", vi: "Trình phát Android" },
    caption: { en: "[ANDROID PLAYER MEDIA REQUIRED]", vi: "[CẦN MEDIA ANDROID]" },
    capabilityIds: ["cap-android-player"],
    maturity: "development",
    customerSensitive: false,
    publicApproved: false,
    altText: { en: "Android display player", vi: "Trình phát Android" },
    displayOrder: 11,
    status: "placeholder",
    displayMode: "television-frame",
    platform: "android",
    fallbackTreatment: "hide",
  },
  {
    id: "media-webos-player",
    title: { en: "LG webOS player", vi: "Trình phát LG webOS" },
    caption: { en: "[WEBOS PLAYER MEDIA REQUIRED]", vi: "[CẦN MEDIA WEBOS]" },
    capabilityIds: ["cap-webos"],
    maturity: "development",
    customerSensitive: false,
    publicApproved: false,
    altText: { en: "webOS display app", vi: "Ứng dụng webOS" },
    displayOrder: 12,
    status: "placeholder",
    displayMode: "television-frame",
    platform: "webos",
    fallbackTreatment: "hide",
  },
  {
    id: "media-playlist",
    title: { en: "Playlist management", vi: "Quản lý playlist" },
    caption: { en: "[PLAYLIST MEDIA REQUIRED]", vi: "[CẦN MEDIA PLAYLIST]" },
    capabilityIds: ["cap-playlist"],
    proofIds: ["proof-playlist"],
    maturity: "development",
    customerSensitive: false,
    publicApproved: false,
    altText: { en: "Playlist management", vi: "Quản lý playlist" },
    displayOrder: 13,
    status: "placeholder",
    displayMode: "dashboard-frame",
    fallbackTreatment: "hide",
  },
  {
    id: "media-diagnostics",
    title: { en: "Diagnostics", vi: "Chẩn đoán" },
    caption: { en: "[DIAGNOSTICS MEDIA REQUIRED]", vi: "[CẦN MEDIA CHẨN ĐOÁN]" },
    capabilityIds: ["cap-diagnostics"],
    maturity: "development",
    customerSensitive: false,
    publicApproved: false,
    altText: { en: "Device diagnostics", vi: "Chẩn đoán thiết bị" },
    displayOrder: 14,
    status: "placeholder",
    displayMode: "dashboard-frame",
    fallbackTreatment: "hide",
  },
  {
    id: "media-physical",
    title: { en: "Physical business surfaces", vi: "Bề mặt kinh doanh vật lý" },
    caption: {
      en: "[PHYSICAL INSTALLATION PHOTO REQUIRED]",
      vi: "[CẦN ẢNH LẮP ĐẶT VẬT LÝ]",
    },
    capabilityIds: ["cap-signage-scheduling"],
    maturity: "pilot",
    customerSensitive: true,
    customerApproval: false,
    publicApproved: false,
    altText: { en: "Physical installation", vi: "Lắp đặt vật lý" },
    displayOrder: 15,
    status: "placeholder",
    displayMode: "physical-installation",
    fallbackTreatment: "hide",
  },
  {
    id: "media-qr-loop",
    title: { en: "QR / physical-to-digital", vi: "QR / vật lý–số" },
    caption: { en: "[QR INTERACTION MEDIA REQUIRED]", vi: "[CẦN MEDIA QR]" },
    maturity: "development",
    customerSensitive: false,
    publicApproved: false,
    altText: { en: "QR interaction", vi: "Tương tác QR" },
    displayOrder: 16,
    status: "placeholder",
    displayMode: "evidence-strip",
    fallbackTreatment: "hide",
  },
];

export function canRenderMediaPublicly(media: ProductMediaAsset): boolean {
  if (!media.publicApproved || !media.assetPath) return false;
  if (media.status === "confidential" || media.status === "not_for_public_site") return false;
  if (media.status === "placeholder" || media.status === "needs_source") return false;
  if (
    media.confidentiality === "confidential" ||
    media.confidentiality === "not_for_public_site"
  ) {
    return false;
  }
  if (media.customerSensitive && !media.customerApproval) return false;
  return true;
}

export function getPublicMedia(list: ProductMediaAsset[] = productMedia) {
  return list.filter(canRenderMediaPublicly).sort((a, b) => a.displayOrder - b.displayOrder);
}

export function getMediaFallbacks(list: ProductMediaAsset[] = productMedia) {
  return list.filter((m) => !canRenderMediaPublicly(m));
}

export function shouldShowMediaGallery(list: ProductMediaAsset[] = productMedia) {
  return getPublicMedia(list).length > 0;
}
